// Today is 2026-05-07. 60 communications entries.
// Types: email, sms, call, note
// Directions: inbound, outbound
// Created by: Tony, Mike, System

export const communications = [
  {
    id: "comm_001",
    customerId: "cust_001",
    customerName: "BMW Vancouver",
    type: "email" as const,
    direction: "outbound" as const,
    subject: "Booking Confirmation — BMW M3 Diamond Cut, Feb 12",
    body: "Hi Derek, confirming your booking for Diamond Cut on the M3 (Brooklyn Grey) on February 12 at 8 AM. Please drop off wheels by 7:45 AM. Thank you!",
    createdAt: "2026-02-05T09:00:00.000Z",
    createdBy: "System",
    relatedTo: { type: "booking" as const, id: "book_003" },
  },
  {
    id: "comm_002",
    customerId: "cust_007",
    customerName: "Ethan Kowalski",
    type: "email" as const,
    direction: "outbound" as const,
    subject: "Invoice WW-2026-001 — Diamond Cut, Porsche 911",
    body: "Hi Ethan, please find your invoice attached for the Diamond Cut service on your Porsche 911 Carrera S. Total: $1,260 incl. GST. Thank you for choosing Western Wheelcraft!",
    createdAt: "2026-02-09T17:05:00.000Z",
    createdBy: "System",
    relatedTo: { type: "invoice" as const, id: "inv_001" },
  },
  {
    id: "comm_003",
    customerId: "cust_007",
    customerName: "Ethan Kowalski",
    type: "email" as const,
    direction: "inbound" as const,
    subject: "Re: Invoice WW-2026-001",
    body: "Payment sent via Interac e-Transfer. Let me know if you need anything else. Great work as always!",
    createdAt: "2026-02-11T10:10:00.000Z",
    createdBy: "Tony",
    relatedTo: { type: "invoice" as const, id: "inv_001" },
  },
  {
    id: "comm_004",
    customerId: "cust_002",
    customerName: "Ferrari Vancouver",
    type: "call" as const,
    direction: "inbound" as const,
    subject: "Trade Inquiry — Ferrari SF90 Wheels",
    body: "Marco Bellini called to confirm drop-off procedure for the SF90 Stradale wheel set. Confirmed Tuesday Feb 18 at 8 AM. Requested branded bags on return.",
    createdAt: "2026-02-10T11:00:00.000Z",
    createdBy: "Tony",
    relatedTo: { type: "booking" as const, id: "book_006" },
  },
  {
    id: "comm_005",
    customerId: "cust_002",
    customerName: "Ferrari Vancouver",
    type: "note" as const,
    direction: "outbound" as const,
    subject: "Internal — SF90 Wheel Handling Note",
    body: "All four wheels wrapped in padded bags. Extra care with the forged spokes — no impact tools. Tony + Mike both present for service.",
    createdAt: "2026-02-18T08:00:00.000Z",
    createdBy: "Mike",
    relatedTo: { type: "booking" as const, id: "book_006" },
  },
  {
    id: "comm_006",
    customerId: "cust_022",
    customerName: "Lauren Stewart",
    type: "sms" as const,
    direction: "outbound" as const,
    subject: "Appointment Reminder — Diamond Cut, Feb 23",
    body: "Hi Lauren, just a reminder your diamond cut appointment is tomorrow (Feb 23) at 9 AM. See you then! — Western Wheelcraft",
    createdAt: "2026-02-22T09:00:00.000Z",
    createdBy: "System",
    relatedTo: { type: "booking" as const, id: "book_008" },
  },
  {
    id: "comm_007",
    customerId: "cust_022",
    customerName: "Lauren Stewart",
    type: "sms" as const,
    direction: "inbound" as const,
    subject: "Reply — Confirmed for tomorrow",
    body: "Thanks, see you at 9! Can you also look at the front-right — has a small chip.",
    createdAt: "2026-02-22T09:45:00.000Z",
    createdBy: "Tony",
    relatedTo: { type: "booking" as const, id: "book_008" },
  },
  {
    id: "comm_008",
    customerId: "cust_018",
    customerName: "Sarah Lee",
    type: "email" as const,
    direction: "outbound" as const,
    subject: "Invoice WW-2026-041 — Payment Overdue",
    body: "Hi Sarah, this is a friendly reminder that invoice WW-2026-041 for $1,470 was due May 2, 2026 and remains unpaid. Please arrange payment at your earliest convenience. Thank you.",
    createdAt: "2026-05-04T10:00:00.000Z",
    createdBy: "Tony",
    relatedTo: { type: "invoice" as const, id: "inv_041" },
  },
  {
    id: "comm_009",
    customerId: "cust_018",
    customerName: "Sarah Lee",
    type: "email" as const,
    direction: "outbound" as const,
    subject: "Second Notice — Invoice WW-2026-041 Overdue",
    body: "Hi Sarah, this is a second notice regarding your outstanding invoice WW-2026-041 for $1,470. Please contact us to arrange payment. We have also attempted to process your card on file which was declined.",
    createdAt: "2026-05-06T10:00:00.000Z",
    createdBy: "Tony",
    relatedTo: { type: "invoice" as const, id: "inv_041" },
  },
  {
    id: "comm_010",
    customerId: "cust_018",
    customerName: "Sarah Lee",
    type: "note" as const,
    direction: "outbound" as const,
    subject: "Internal Note — Sarah Lee Overdue",
    body: "Card attempted May 3 — declined (pay_045). Two email reminders sent. If no response by May 14, send final notice and consider sending to collections.",
    createdAt: "2026-05-06T10:30:00.000Z",
    createdBy: "Tony",
    relatedTo: { type: "invoice" as const, id: "inv_041" },
  },
  {
    id: "comm_011",
    customerId: "cust_025",
    customerName: "Eric Johansson",
    type: "email" as const,
    direction: "inbound" as const,
    subject: "Booking Request — Bentayga EWB",
    body: "Hi Tony, I'd like to book the Bentayga EWB wheels for OEM match. Same quality as the Urus set, please. Available April 25?",
    createdAt: "2026-04-18T09:00:00.000Z",
    createdBy: "Tony",
    relatedTo: { type: "booking" as const, id: "book_092" },
  },
  {
    id: "comm_012",
    customerId: "cust_025",
    customerName: "Eric Johansson",
    type: "email" as const,
    direction: "outbound" as const,
    subject: "Re: Booking Request — Bentayga EWB Confirmed",
    body: "Hi Eric, confirmed for April 25 at 8 AM. Same care as always — detail included. We look forward to seeing you.",
    createdAt: "2026-04-18T14:00:00.000Z",
    createdBy: "Tony",
    relatedTo: { type: "booking" as const, id: "book_092" },
  },
  {
    id: "comm_013",
    customerId: "cust_011",
    customerName: "Aiden McAllister",
    type: "sms" as const,
    direction: "outbound" as const,
    subject: "Appointment Reminder — Diamond Cut, May 7",
    body: "Hi Aiden, your diamond cut is booked for tomorrow, May 7 at 8 AM. Drop off at rear entrance. — Western Wheelcraft",
    createdAt: "2026-05-06T09:00:00.000Z",
    createdBy: "System",
    relatedTo: { type: "booking" as const, id: "book_051" },
  },
  {
    id: "comm_014",
    customerId: "cust_011",
    customerName: "Aiden McAllister",
    type: "sms" as const,
    direction: "inbound" as const,
    subject: "Reply — Confirmed",
    body: "All good! See you at 8.",
    createdAt: "2026-05-06T09:30:00.000Z",
    createdBy: "Tony",
    relatedTo: { type: "booking" as const, id: "book_051" },
  },
  {
    id: "comm_015",
    customerId: "cust_005",
    customerName: "Porsche Centre Vancouver",
    type: "call" as const,
    direction: "inbound" as const,
    subject: "Rush Request — Cayenne Turbo GT",
    body: "Lena Schmidt called requesting rush turnaround on the Cayenne Turbo GT wheels for pre-delivery. Confirmed April 29 at 8 AM. Rush surcharge discussed and approved.",
    createdAt: "2026-04-22T10:00:00.000Z",
    createdBy: "Tony",
    relatedTo: { type: "booking" as const, id: "book_043" },
  },
  {
    id: "comm_016",
    customerId: "cust_006",
    customerName: "McLaren Vancouver",
    type: "email" as const,
    direction: "inbound" as const,
    subject: "Upcoming — Artura Wheels",
    body: "Chris Bolton here. We'll have the Artura wheels ready for drop-off May 23 morning. All forged — please ensure specialist technician assigned.",
    createdAt: "2026-05-06T09:00:00.000Z",
    createdBy: "Mike",
    relatedTo: { type: "booking" as const, id: "book_067" },
  },
  {
    id: "comm_017",
    customerId: "cust_006",
    customerName: "McLaren Vancouver",
    type: "email" as const,
    direction: "outbound" as const,
    subject: "Re: Artura — Confirmed May 23",
    body: "Hi Chris, confirmed for May 23 at 8 AM. Mike will handle the Artura wheels personally. All crew will be briefed on forged wheel protocol.",
    createdAt: "2026-05-06T14:00:00.000Z",
    createdBy: "Tony",
    relatedTo: { type: "booking" as const, id: "book_067" },
  },
  {
    id: "comm_018",
    customerId: "cust_027",
    customerName: "Alex Patel",
    type: "sms" as const,
    direction: "outbound" as const,
    subject: "Appointment Reminder — Mobile Service, May 7 11 AM",
    body: "Hi Alex, your mobile curb rash repair is scheduled for today at 11 AM at your condo (Helmcken St). Our tech will buzz unit 312. — Western Wheelcraft",
    createdAt: "2026-05-07T08:00:00.000Z",
    createdBy: "System",
    relatedTo: { type: "booking" as const, id: "book_053" },
  },
  {
    id: "comm_019",
    customerId: "cust_027",
    customerName: "Alex Patel",
    type: "sms" as const,
    direction: "inbound" as const,
    subject: "Reply — Ready",
    body: "Perfect, I'll be home. Parking spot #32 in the basement.",
    createdAt: "2026-05-07T08:15:00.000Z",
    createdBy: "Tony",
    relatedTo: { type: "booking" as const, id: "book_053" },
  },
  {
    id: "comm_020",
    customerId: "cust_052",
    customerName: "Valentina Cruz",
    type: "email" as const,
    direction: "inbound" as const,
    subject: "Instagram DM — Range Rover Quote Request",
    body: "Hi! I found you on Instagram. I have a 2024 Range Rover Autobiography with 23-inch wheels — clear coat peeling and some scuffs. Can I get a quote? Located in West Vancouver.",
    createdAt: "2026-04-10T10:00:00.000Z",
    createdBy: "Tony",
    relatedTo: { type: "quote" as const, id: "quote_011" },
  },
  {
    id: "comm_021",
    customerId: "cust_052",
    customerName: "Valentina Cruz",
    type: "email" as const,
    direction: "outbound" as const,
    subject: "Quote WW — Range Rover Autobiography OEM Colour Match",
    body: "Hi Valentina, thank you for reaching out! Please find your quote attached for OEM Colour Match on all 4 wheels of your Range Rover Autobiography. Estimated total: $2,200 + GST.",
    createdAt: "2026-04-11T10:00:00.000Z",
    createdBy: "Tony",
    relatedTo: { type: "quote" as const, id: "quote_011" },
  },
  {
    id: "comm_022",
    customerId: "cust_003",
    customerName: "Mercedes-Benz Burnaby",
    type: "email" as const,
    direction: "inbound" as const,
    subject: "RE: Invoice WW-2026-030",
    body: "Hi Tony, confirming invoice WW-2026-030 received. Processing with Sandra Yee this week. Thank you.",
    createdAt: "2026-04-03T10:00:00.000Z",
    createdBy: "Tony",
    relatedTo: { type: "invoice" as const, id: "inv_030" },
  },
  {
    id: "comm_023",
    customerId: "cust_009",
    customerName: "Marcus Chen",
    type: "call" as const,
    direction: "inbound" as const,
    subject: "Custom Quote Follow-up — Two-Tone IS500",
    body: "Marcus called to confirm colour swatch selection: gloss black outer barrel + machined face centre. Approved over the phone. Tony noted on file.",
    createdAt: "2026-02-18T11:00:00.000Z",
    createdBy: "Tony",
    relatedTo: { type: "booking" as const, id: "book_010" },
  },
  {
    id: "comm_024",
    customerId: "cust_032",
    customerName: "Samantha Clarke",
    type: "email" as const,
    direction: "inbound" as const,
    subject: "Referral from Lauren Stewart",
    body: "Hi, Lauren Stewart recommended your shop. I'd like to book a two-tone custom finish on my BMW 430i Convertible (Portimao Blue, 20-inch aftermarket wheels). When's the earliest?",
    createdAt: "2026-04-24T11:00:00.000Z",
    createdBy: "Tony",
    relatedTo: null,
  },
  {
    id: "comm_025",
    customerId: "cust_032",
    customerName: "Samantha Clarke",
    type: "email" as const,
    direction: "outbound" as const,
    subject: "Re: Two-Tone Custom — BMW 430i, April 30 Confirmed",
    body: "Hi Samantha! Great to hear from you — Lauren is one of our favourite clients. We have April 30 at 9 AM available. We'll do gloss black outer + polished face. Deposit of $900 to secure.",
    createdAt: "2026-04-24T14:00:00.000Z",
    createdBy: "Tony",
    relatedTo: { type: "booking" as const, id: "book_044" },
  },
  {
    id: "comm_026",
    customerId: "cust_028",
    customerName: "Rachel Kim",
    type: "note" as const,
    direction: "outbound" as const,
    subject: "5-Star Google Review — Rachel Kim",
    body: "Rachel left a 5-star review: 'Best wheel shop in Vancouver. My G Wagon looks incredible. Professional, fast, and fair pricing. Will not go anywhere else!' Respond publicly.",
    createdAt: "2026-03-17T14:00:00.000Z",
    createdBy: "Tony",
    relatedTo: null,
  },
  {
    id: "comm_027",
    customerId: "cust_013",
    customerName: "Jordan Fitzgerald",
    type: "email" as const,
    direction: "outbound" as const,
    subject: "Overdue Invoice WW-2026-042 — Payment Reminder",
    body: "Hi Jordan, invoice WW-2026-042 for $504 was due April 8 and remains outstanding. Please arrange payment via e-Transfer or card. Thank you.",
    createdAt: "2026-04-15T10:00:00.000Z",
    createdBy: "Tony",
    relatedTo: { type: "invoice" as const, id: "inv_042" },
  },
  {
    id: "comm_028",
    customerId: "cust_013",
    customerName: "Jordan Fitzgerald",
    type: "email" as const,
    direction: "inbound" as const,
    subject: "Re: Overdue Invoice",
    body: "Hi Tony, sorry about that — cash flow was tight. I'll send the e-Transfer this week. Also want to book a colour match for my Type R — can we discuss?",
    createdAt: "2026-04-16T09:00:00.000Z",
    createdBy: "Tony",
    relatedTo: { type: "invoice" as const, id: "inv_042" },
  },
  {
    id: "comm_029",
    customerId: "cust_049",
    customerName: "Noah Sinclair",
    type: "call" as const,
    direction: "inbound" as const,
    subject: "Follow-up — Escalade V Rear Set",
    body: "Noah called asking about a second two-tone set for the rear axle of the Escalade. Same spec as the front set done April 17. Booked for May 16.",
    createdAt: "2026-05-03T14:00:00.000Z",
    createdBy: "Tony",
    relatedTo: { type: "booking" as const, id: "book_062" },
  },
  {
    id: "comm_030",
    customerId: "cust_040",
    customerName: "James Okafor",
    type: "sms" as const,
    direction: "inbound" as const,
    subject: "Feedback — Purple Powder Coat",
    body: "Tony the wheels look absolutely amazing!! Everyone at the meet was asking about them. Already want to book again — diamond cut this time?",
    createdAt: "2026-04-05T12:00:00.000Z",
    createdBy: "Tony",
    relatedTo: { type: "booking" as const, id: "book_028" },
  },
  {
    id: "comm_031",
    customerId: "cust_040",
    customerName: "James Okafor",
    type: "sms" as const,
    direction: "outbound" as const,
    subject: "Re: Diamond Cut Follow-up",
    body: "Glad you love them! Yes absolutely — we can do a diamond cut pass. Booked you for May 14 at 9 AM. Deposit link incoming.",
    createdAt: "2026-04-05T12:30:00.000Z",
    createdBy: "Tony",
    relatedTo: { type: "booking" as const, id: "book_060" },
  },
  {
    id: "comm_032",
    customerId: "cust_004",
    customerName: "Audi Downtown Vancouver",
    type: "email" as const,
    direction: "inbound" as const,
    subject: "Upcoming Batch — RS7 + Q8 e-tron",
    body: "Hi Tony, James Park here. We'll have the RS7 wheels ready for March 6 and the Q8 e-tron for April 21. Both OEM match. Please send invoices net-30 as usual.",
    createdAt: "2026-03-01T08:30:00.000Z",
    createdBy: "Tony",
    relatedTo: null,
  },
  {
    id: "comm_033",
    customerId: "cust_016",
    customerName: "Natasha Volkov",
    type: "call" as const,
    direction: "inbound" as const,
    subject: "Booking Inquiry — C300",
    body: "Natasha called asking about OEM color match for her C300. Quoted $1,100 for 4 wheels. She wants to book May 22 and will pay the deposit today.",
    createdAt: "2026-05-07T09:00:00.000Z",
    createdBy: "Mike",
    relatedTo: { type: "booking" as const, id: "book_066" },
  },
  {
    id: "comm_034",
    customerId: "cust_045",
    customerName: "Yuki Sato",
    type: "email" as const,
    direction: "outbound" as const,
    subject: "Diamond Cut Inspection Notes — BRZ tS",
    body: "Hi Yuki, your BRZ tS wheels have been completed. We noted that the rear-right had a slightly deeper groove which required extra pass. All four wheels inspected and approved. Ready for pickup.",
    createdAt: "2026-04-24T15:00:00.000Z",
    createdBy: "Mike",
    relatedTo: { type: "booking" as const, id: "book_041" },
  },
  {
    id: "comm_035",
    customerId: "cust_038",
    customerName: "William Fraser",
    type: "note" as const,
    direction: "outbound" as const,
    subject: "Internal — Vintage 964 Wheel Notes",
    body: "964 Carrera RS wheels are from 1992 — magnesium alloy casting, different thermal tolerance. Use low-temp powder cure and no impact tools. Mike to handle June 4 booking personally.",
    createdAt: "2026-05-07T10:00:00.000Z",
    createdBy: "Mike",
    relatedTo: { type: "booking" as const, id: "book_075" },
  },
  {
    id: "comm_036",
    customerId: "cust_014",
    customerName: "Mei Lin",
    type: "sms" as const,
    direction: "outbound" as const,
    subject: "Wheels Ready for Pickup",
    body: "Hi Mei, your Range Rover Sport wheels are ready for pickup. Please collect between 9 AM and 4 PM today. — Western Wheelcraft",
    createdAt: "2026-05-06T14:00:00.000Z",
    createdBy: "System",
    relatedTo: { type: "booking" as const, id: "book_099" },
  },
  {
    id: "comm_037",
    customerId: "cust_014",
    customerName: "Mei Lin",
    type: "sms" as const,
    direction: "inbound" as const,
    subject: "Reply — Pick Up Tomorrow",
    body: "Thank you! I'll come by tomorrow morning around 10.",
    createdAt: "2026-05-06T14:20:00.000Z",
    createdBy: "Tony",
    relatedTo: { type: "booking" as const, id: "book_099" },
  },
  {
    id: "comm_038",
    customerId: "cust_042",
    customerName: "Patrick Leung",
    type: "email" as const,
    direction: "inbound" as const,
    subject: "Fleet Invoice Query — Sprinter",
    body: "Hi Tony, can you make sure future fleet invoices are addressed to Patrick Leung Enterprises Ltd. for our accounting? Same address as before. Thanks.",
    createdAt: "2026-04-10T10:00:00.000Z",
    createdBy: "Tony",
    relatedTo: { type: "invoice" as const, id: "inv_021" },
  },
  {
    id: "comm_039",
    customerId: "cust_042",
    customerName: "Patrick Leung",
    type: "email" as const,
    direction: "outbound" as const,
    subject: "Re: Fleet Invoice Update",
    body: "Hi Patrick, noted — all future invoices will be addressed to Patrick Leung Enterprises Ltd. Updated in our records.",
    createdAt: "2026-04-10T14:00:00.000Z",
    createdBy: "Tony",
    relatedTo: null,
  },
  {
    id: "comm_040",
    customerId: "cust_050",
    customerName: "Fatima Al-Rashid",
    type: "email" as const,
    direction: "inbound" as const,
    subject: "Spring Booking — Tesla Model X",
    body: "Hi, I'd like to book a diamond cut for my Model X for after winter. Please email me only — I don't take calls during work hours. Available April 23?",
    createdAt: "2026-04-16T10:00:00.000Z",
    createdBy: "Tony",
    relatedTo: { type: "booking" as const, id: "book_040" },
  },
  {
    id: "comm_041",
    customerId: "cust_050",
    customerName: "Fatima Al-Rashid",
    type: "email" as const,
    direction: "outbound" as const,
    subject: "Re: Spring Diamond Cut — April 23 Confirmed",
    body: "Hi Fatima, confirmed for April 23 at 9 AM. We'll communicate by email only as requested. Deposit invoice attached.",
    createdAt: "2026-04-16T14:00:00.000Z",
    createdBy: "Tony",
    relatedTo: { type: "booking" as const, id: "book_040" },
  },
  {
    id: "comm_042",
    customerId: "cust_019",
    customerName: "Connor MacDonald",
    type: "email" as const,
    direction: "inbound" as const,
    subject: "Shipping Wheels for Diamond Cut — Corvette Z06",
    body: "Hi, I'm shipping the Corvette Z06 wheels from Victoria on April 10. Should arrive by April 12. Please do diamond cut on all four. Pickup to be arranged.",
    createdAt: "2026-04-09T10:00:00.000Z",
    createdBy: "Tony",
    relatedTo: { type: "booking" as const, id: "book_108" },
  },
  {
    id: "comm_043",
    customerId: "cust_019",
    customerName: "Connor MacDonald",
    type: "email" as const,
    direction: "outbound" as const,
    subject: "Re: Corvette Z06 — Received, Booked April 13",
    body: "Hi Connor, wheels received in good condition. Booked for April 13. We'll email photos on completion and arrange return courier.",
    createdAt: "2026-04-12T10:00:00.000Z",
    createdBy: "Tony",
    relatedTo: { type: "booking" as const, id: "book_108" },
  },
  {
    id: "comm_044",
    customerId: "cust_015",
    customerName: "Daniel Park",
    type: "call" as const,
    direction: "inbound" as const,
    subject: "First Booking — Tesla Model S (Referred by Ethan)",
    body: "Daniel called — referred by Ethan Kowalski. Wants curb rash repair on 2 wheels of his Tesla Model S Plaid. Booked April 9. Confirmed deposit by card over the phone.",
    createdAt: "2026-04-02T11:00:00.000Z",
    createdBy: "Tony",
    relatedTo: { type: "booking" as const, id: "book_032" },
  },
  {
    id: "comm_045",
    customerId: "cust_051",
    customerName: "Owen Bergstrom",
    type: "email" as const,
    direction: "inbound" as const,
    subject: "Second Booking — 4Runner After Tundra",
    body: "Tony, the Tundra looks amazing. Want to do the same satin black on the 4Runner's 17s. Can we do June 5?",
    createdAt: "2026-05-05T10:00:00.000Z",
    createdBy: "Tony",
    relatedTo: { type: "booking" as const, id: "book_076" },
  },
  {
    id: "comm_046",
    customerId: "cust_051",
    customerName: "Owen Bergstrom",
    type: "email" as const,
    direction: "outbound" as const,
    subject: "Re: 4Runner June 5 — Confirmed",
    body: "Hi Owen, great to hear! June 5 at 9 AM confirmed for the 4Runner TRD Pro — satin black, same spec as the Tundra. Deposit invoice attached.",
    createdAt: "2026-05-05T14:00:00.000Z",
    createdBy: "Tony",
    relatedTo: { type: "booking" as const, id: "book_076" },
  },
  {
    id: "comm_047",
    customerId: "cust_017",
    customerName: "Ryan Dubois",
    type: "sms" as const,
    direction: "outbound" as const,
    subject: "Appointment Reminder — Diamond Cut, April 26",
    body: "Hi Ryan, reminder: your diamond cut on the Mustang Dark Horse is tomorrow April 26 at 9 AM. See you then! — Western Wheelcraft",
    createdAt: "2026-04-25T09:00:00.000Z",
    createdBy: "System",
    relatedTo: { type: "booking" as const, id: "book_093" },
  },
  {
    id: "comm_048",
    customerId: "cust_024",
    customerName: "Amelia Watson",
    type: "email" as const,
    direction: "inbound" as const,
    subject: "Quote Request — Defender 110 OEM Match",
    body: "Hi, I have a 2024 Land Rover Defender 110 in Pangea Green with 22-inch wheels. Two are damaged from a curb, all four need OEM match for consistency. Can I get a quote?",
    createdAt: "2026-05-04T10:00:00.000Z",
    createdBy: "Tony",
    relatedTo: { type: "quote" as const, id: "quote_029" },
  },
  {
    id: "comm_049",
    customerId: "cust_024",
    customerName: "Amelia Watson",
    type: "email" as const,
    direction: "outbound" as const,
    subject: "Quote — Defender 110 OEM Color Match 4 Wheels",
    body: "Hi Amelia, thank you! Quote attached for OEM colour match on all 4 wheels of your Defender 110 (Pangea Green). Total estimate: $1,600 + GST. Deposit of 50% secures your booking.",
    createdAt: "2026-05-05T09:00:00.000Z",
    createdBy: "Tony",
    relatedTo: { type: "quote" as const, id: "quote_029" },
  },
  {
    id: "comm_050",
    customerId: "cust_033",
    customerName: "Derek Lam",
    type: "email" as const,
    direction: "outbound" as const,
    subject: "Overdue Invoice WW-2026-043 — Payment Reminder",
    body: "Hi Derek, invoice WW-2026-043 for $294 was due March 20 and remains outstanding. This is for the curb rash repair on your Ioniq 6. Please arrange payment. Thank you.",
    createdAt: "2026-04-01T10:00:00.000Z",
    createdBy: "Tony",
    relatedTo: { type: "invoice" as const, id: "inv_043" },
  },
  {
    id: "comm_051",
    customerId: "cust_020",
    customerName: "Isabelle Gagne",
    type: "email" as const,
    direction: "inbound" as const,
    subject: "Two-Tone Booking Enquiry — RS5 Sportback",
    body: "Hi, I'd like a two-tone custom finish on my Audi RS5 Sportback aftermarket 20s. Thinking gloss black outer + polished spoke face. Can you do May 8?",
    createdAt: "2026-05-02T11:00:00.000Z",
    createdBy: "Tony",
    relatedTo: { type: "booking" as const, id: "book_057" },
  },
  {
    id: "comm_052",
    customerId: "cust_020",
    customerName: "Isabelle Gagne",
    type: "email" as const,
    direction: "outbound" as const,
    subject: "Re: Two-Tone Custom — May 8 Confirmed",
    body: "Hi Isabelle, perfect — May 8 at 10 AM confirmed. Gloss black outer + polished spoke face. Deposit of $900 to secure. Looking forward to it!",
    createdAt: "2026-05-02T14:00:00.000Z",
    createdBy: "Tony",
    relatedTo: { type: "booking" as const, id: "book_057" },
  },
  {
    id: "comm_053",
    customerId: "cust_037",
    customerName: "Jade Nakamura",
    type: "call" as const,
    direction: "inbound" as const,
    subject: "Mobile Service Booking — OEM Match, May 19",
    body: "Jade called requesting mobile service at her condo for OEM match on all 4 NX wheels. Confirmed May 19 at 11 AM. Parking noted — same spot as last time.",
    createdAt: "2026-05-06T11:00:00.000Z",
    createdBy: "Mike",
    relatedTo: { type: "booking" as const, id: "book_063" },
  },
  {
    id: "comm_054",
    customerId: "cust_047",
    customerName: "Cameron Ross",
    type: "sms" as const,
    direction: "outbound" as const,
    subject: "Wheels Ready — Charger Scat Pack",
    body: "Hi Cameron, your Charger Scat Pack diamond cut wheels are done and ready for pickup! — Western Wheelcraft",
    createdAt: "2026-05-02T15:00:00.000Z",
    createdBy: "System",
    relatedTo: { type: "booking" as const, id: "book_097" },
  },
  {
    id: "comm_055",
    customerId: "cust_047",
    customerName: "Cameron Ross",
    type: "sms" as const,
    direction: "inbound" as const,
    subject: "Reply — Coming Tomorrow",
    body: "Awesome! I'll pick them up tomorrow morning.",
    createdAt: "2026-05-02T15:30:00.000Z",
    createdBy: "Tony",
    relatedTo: { type: "booking" as const, id: "book_097" },
  },
  {
    id: "comm_056",
    customerId: "cust_030",
    customerName: "Vivian Zhao",
    type: "email" as const,
    direction: "inbound" as const,
    subject: "Invoice Question — WW-2026-035",
    body: "Hi, I received invoice WW-2026-035. Is e-Transfer okay? I'll send it by May 10.",
    createdAt: "2026-04-23T11:00:00.000Z",
    createdBy: "Tony",
    relatedTo: { type: "invoice" as const, id: "inv_035" },
  },
  {
    id: "comm_057",
    customerId: "cust_030",
    customerName: "Vivian Zhao",
    type: "email" as const,
    direction: "outbound" as const,
    subject: "Re: Invoice WW-2026-035 — e-Transfer Fine",
    body: "Hi Vivian, e-Transfer is perfect. Please send to payments@westernwheelcraft.ca. Thank you!",
    createdAt: "2026-04-23T14:00:00.000Z",
    createdBy: "Tony",
    relatedTo: { type: "invoice" as const, id: "inv_035" },
  },
  {
    id: "comm_058",
    customerId: "cust_023",
    customerName: "Kevin Huang",
    type: "note" as const,
    direction: "outbound" as const,
    subject: "Internal — Kevin Huang Invoice Follow-up",
    body: "Invoice WW-2026-039 for $630 borderline overdue (due May 3). Client said e-Transfer was incoming. Follow up by May 8 if not received.",
    createdAt: "2026-05-05T10:00:00.000Z",
    createdBy: "Tony",
    relatedTo: { type: "invoice" as const, id: "inv_039" },
  },
  {
    id: "comm_059",
    customerId: "cust_022",
    customerName: "Lauren Stewart",
    type: "call" as const,
    direction: "inbound" as const,
    subject: "Referral — Samantha Clarke",
    body: "Lauren called to refer her colleague Samantha Clarke for a two-tone custom job. Said Samantha has a blue BMW convertible with 20-inch aftermarkets. Happy to connect them.",
    createdAt: "2026-04-23T10:00:00.000Z",
    createdBy: "Tony",
    relatedTo: null,
  },
  {
    id: "comm_060",
    customerId: "cust_007",
    customerName: "Ethan Kowalski",
    type: "sms" as const,
    direction: "outbound" as const,
    subject: "Appointment Reminder — OEM Match, May 8",
    body: "Hi Ethan, reminding you of your OEM colour match appointment tomorrow May 8 at 8 AM. Storage wheels looking fresh — see you then! — Western Wheelcraft",
    createdAt: "2026-05-07T09:00:00.000Z",
    createdBy: "System",
    relatedTo: { type: "booking" as const, id: "book_055" },
  },
];

export type Communication = (typeof communications)[number];

export default communications;
